[nsfw]
content_warnings = ["Incest"]
about = """
Videah does not have canonical genitals. They change depending on what I'm feeling in the moment.

He usually has an uncut human penis that is about 6 inches, but sometimes has other genitalia like a canine vagina or null.

Videah is a switch but mostly prefers to bottom.
"""

[credit."cocadope.png"]
handle = "@Cocadope"
