[credit."/videah/gallery/cocadope.png"]
handle = "Cocadope"
url = "https://twitter.com/Cocadope"

[credit."/videah/gallery/jet_set_videah_wikipixel.png"]
handle = "WIKIPIXEL"
url = "https://wikipixel.carrd.co"

[credit."/videah/gallery/videah__SymmetryPainting.png"]
handle = "Huie"
url = "https://huie.carrd.co"

[credit."/videah/gallery/tatsu.png"]
handle = "Tatsu"
url = "https://axontatsu.carrd.co"

[credit."/videah/gallery/tatsu 2.png"]
handle = "Tatsu"
url = "https://axontatsu.carrd.co"

[credit."/videah/gallery/rinrinwolf_sketch.png"]
handle = "rinrinwolf"
url = "https://rinrinwolf.wixsite.com/wawoom"

[credit."/videah/gallery/subi_3.png"]
handle = "SUBI"
url = "https://myotomimyouhu.jimdofree.com"

[credit."/videah/gallery/scruff.png"]
handle = "Scruff"
url = "https://scruffkerfluff.carrd.co"

[credit."/videah/gallery/paws.png"]
handle = "KazuK9"
url = "https://www.kazuk9.com"

[credit."/videah/gallery/cowboy.png"]
handle = "Kurumiken"
url = "https://twitter.com/kurumiken"

[credit."/videah/gallery/were-videah.png"]
handle = "skullsbesan"
url = "https://twitter.com/skullsbesan"

[credit."/videah/gallery/Videah.png"]
handle = "Tatujapa"
url = "https://linktr.ee/tatujapa"

[credit."/videah/gallery/small_orf_ref.jpg"]
handle = "orf"
url = "https://twitter.com/justlikeorf"
